use_frameworks!
use_modular_headers!
source "https://github.com/mintforpeople/mint-podspec-repo.git"
source "https://github.com/CocoaPods/Specs.git"

target 'robobo-remote-control-ws-ios_Example' do
  pod 'robobo-framework-ios-pod','~>0.1.0'
  pod 'robobo-remote-control-ios','~>0.1.2'
  pod 'robobo-remote-control-ws-ios', :path => '../'
  pod 'robobo-sensing-ios','~>0.1.2'

  pod 'PocketSocket'
  target 'robobo-remote-control-ws-ios_Tests' do
    inherit! :search_paths

    
  end
end
